### ISSUE TITLE
DllNotFoundException: fluidsynth

### ISSUE THREAD

**Issue by Injazz** [atsushieno/nfluidsynth#2]
When trying to run `NFluidsynth.Sample`, it crashes with unhandled exception `DllNotFoundException: fluidsynth`

**Comment by atsushieno** [comment]
nfluidsynth itself is just a managed P/Invoke library. You have to get fluidsynth.dll, libfluidsynth.dylib, or libfluidsynth.so, depending on your platform and place it either on the same directory as nfluidsynth.dll or in some PATH that your runtime (.NET or Mono) can load.
