### ISSUE TITLE
.nuspec does not specify all dependency groups

### ISSUE THREAD

**Issue by PJB3005** [atsushieno/nfluidsynth#6]
This also means there isn't a dependency on `System.Memory` marked for net472, which I believe means it won't properly work?

Anyways, using groups in the nuspec should make it show up better on NuGet and fix the `System.Memory` issue:

```xml
    <dependencies>
      <group targetFramework=".NETFramework4.7.2">
        <dependency id="System.Memory" version="4.5.3" exclude="Build,Analyzers" />
      </group>
      <group targetFramework=".NETCoreApp3.0" />
      <group targetFramework=".NETStandard2.0">
        <dependency id="System.Memory" version="4.5.3" exclude="Build,Analyzers" />
      </group>
    </dependencies>
```

**Comment by atsushieno** [comment]
done at v0.2.5.

**Comment by PJB3005** [comment]
> Thanks but netstandard2.0 build does not depend on System.Memory. Other parts will be taken.
Neither is it in `net472`. That's why you specify it as a dependency so NuGet pulls it in.

**Comment by atsushieno** [comment]
I thought you were talking about dependencies on `Span<T>` etc. Dependencies on those types are enabled only in `#if NET472 || NETCOREAPP`.

**Comment by PJB3005** [comment]
Yes. That's what I'm talking about. `net472` doesn't have `Span<T>` either, just like `netstandard2.0`. That's why the `net472` build has an explicit dependency on `System.Memory`, so those types become available.

> Note that System.Memory.dll is not available in Xamarin.Android framework libraries in the latest packaged build of it.

Do you mean `System.Memory` from NuGet does not work on Android at all or is this just "it is not included by default" like how it is on Framework.

If not, you should just drop the `#if NET472 || NETCOREAPP` and add an explicit NuGet dependency for `System.Memory` to the `netstandard2.0` build. Then you don't have weird API compatibility issues and all that.

**Comment by atsushieno** [comment]
Yes I meant that.

**Comment by PJB3005** [comment]
Ah, ok. I didn't know that. That's fair.
