### ISSUE TITLE
Unable to find fluidsynth.dll

### ISSUE THREAD

**Issue by Yorgg** [atsushieno/nfluidsynth#8]
I'm having some trouble connecting to the fluidsynth.dll.

steps: 

1. I build the .dll on Windows using msys2:  https://github.com/FluidSynth/fluidsynth/wiki/BuildingWithCMake#building-with-msys2-on-windows

2. Then on `/build/src/ ` I find `libfluidsynth-2.dll`  (this the correct .dll file I hope?)

3. I copy this file into my **Unity Assets folder**, and rename it to `fluidsynth.dll`

4. On Unity I get a `DllNotFound exception: fluidsynth`.  

I tried this with fluidsynths versions 2.1.3, and 2.0.8.

Do you know what I'm doing wrong here?  thanks!

**Comment by atsushieno** [comment]
I haven't written any code with Unity so I barely have ideas, but looks like the directory structure is more complicated than just putting the files directly into Unity Assets folder? : https://ericeastwood.com/blog/17/unity-and-dlls-c-managed-and-c-unmanaged

I believe that `fuildsynth.dll` filename is correct.

**Comment by Yorgg** [comment]
Thanks for the response.  I wanted to be sure that I am using the correct .dll file.   

This is the file I'm using (highlighted): 
![Capture](https://user-images.githubusercontent.com/10824040/87407447-068e7180-c577-11ea-9fb5-9dc260b66f4d.PNG)

I think its loading the .dll - as I am also getting the error: `Plugins: Failed to load 'Assets/Plugins/fluidsynth.dll'  because one or more of its dependencies could not be loaded`

**Comment by atsushieno** [comment]
Wasn't fluidsynth dependent on glib-2.0 etc. ? Unless all those dependencies are statically linked, they also have to be there.

**Comment by Yorgg** [comment]
I used [https://github.com/lucasg/Dependencies](https://github.com/lucasg/Dependencies) and found 13 dependencies.
The error message has disappeared. Thanks!

**Comment by Yorgg** [comment]
By the way, I cannot hear audio when I make a noteon event.  :/

I think this is probably a Unity+fluidsynth issue, [so I made post on fluidsynth repo.  ](https://github.com/FluidSynth/fluidsynth/issues/656)

Would you have any idea what the issue is?

```


 using (var settings = new NFluidsynth.Settings())  {              
                settings[ConfigurationKeys.SynthAudioChannels].IntValue = 2;
                using (var syn = new Synth(settings))
                {
                    syn.LoadSoundFont("/usr/share/sounds/pathtoyoursoundfont.sf2", true);
                    for (int i = 0; i < 16; i++)
                        syn.SoundFontSelect(i, 1);
                   
                        using (var adriver = new AudioDriver(syn.Settings, syn))
                        {
                            syn.ProgramChange(0, 0);
                            syn.NoteOn(0, 60, 120);
                        }
                    }
                }
```

**Comment by atsushieno** [comment]
Try applicable audio drivers that works on your machine? Like this https://github.com/atsushieno/nfluidsynth/blob/master/NFluidsynth.Sample/Program.cs#L15

**Comment by Yorgg** [comment]
I tried all the Windows' audio drivers, but no luck. 
The audio works fine when I open fluidsynth.exe outside of Unity - so maybe the issue is related to the Unity environment. 
Hmm...

**Comment by Yorgg** [comment]
I realized the sound wasn't working because the audio driver was immediately being disposed.   Problem fixed!
